apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
     app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: twu1987/httpserver:latest
        ports:
            - containerPort: 9090
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 1"]    
        startupProbe:
          httpGet:
            port: 9090
            path: /healthz
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 9090
            path: /healthz
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            port: 9090
            path: /healthz
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 100m

        